spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp1fx93r6rj80qypzmo.mysql.rds.aliyuncs.com:3306/jingfang?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: host
    password: Aa62655929
    hikari:
      idle-timeout: 60000
      maximum-pool-size: 30
      minimum-idle: 10

  thymeleaf:
    cache: false

  # 热部署
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      additional-exclude: static/**

  resources:
    cache:
      period: 0

server:
  servlet:
    context-path: /
  port: 8001

# 日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



# 腾讯云SMS的相关参数
tencent:
  secretId: AKIDFQdjnEbuAKRenptqjbJuOwKfy9DA0jKo
  secretKey: SmrnnhP1SgmqjP3sgiXAe52sZ3eAe2KQ
  sms:
    signName: 北京安戈普罗科技有限公司
    templateId: 1980771
    appId: 1400867275

logging:
  level:
    com:
      example: INFO
